# Note that in YAML, boolean values are "true", "false"
zone:
    circle: 100 # False/0 if no circle zone. Float to define the radius
    cross: false # False/0 if no cross zone. Float to define the branch width
    square: false # False/0 if no square zone. Float to define the side length
    wiggle_angle: 45 # Angle (in degrees) of the brownian motion cone

model:
    side_length: 500.0 # Length of the sides of the model
    walls: false # Wether the walls should have collisions
    patches_by_side: 20

particles:
    number: 1000 # Number of particles in the model
    collisions: true # Wether the particles should have collisions
    max_radius: 10.0 # Maximum radius of the particles
    fixed_radius: false # Wether the particles should all have the same size
    start_zero_x: false # Initialize all particles with x = 0? Boolean
    parallel_vel: false # # Wether the particles should all start with a parralel velocity
    fixed_mass: false # Wether the particles should all have the same size
    fixed_k: false # Wether the particles should all have the same repulsive force

simulation:
    output_video: true # true: output a video  "simu.mp4"
    interactive_window: false # true : display an interactive window
    n_steps: 100 # Number of steps of a blind simulation (if no interactive window and no video)